version: '3'

services:
  server:
    build:
      context: ./
      network: host # to fix fetches of 'apk add' commands
    #    restart: always
    ports:
      - '5001:5001'
    env_file: ".env"
    environment:
      DB_HOST: "postgresql"
      DB_PORT: "5432"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:17-alpine
    restart: always
    # ports:
    # - '5433:5432'
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
